### ISSUE TITLE
SSH key injection happens after instance is created, rather than before

### ISSUE THREAD

**Issue by seanhui1** [jenkinsci/google-compute-engine-plugin#100]
Seems like the SSH key injection via the plugin is happening unnecessarily late.

The SSH public key can be appended to the metadata before instance creation, rather than at launch time.

This way startup scripts can reference the ssh keys in metadata.

**Comment by stephenashank** [comment]
Hi @seanhui1, with release 3.2.0 this should be addressed. It may take a few hours to reach the update center in the Jenkins plugin manager. Let us know if you experience any issues.
