### ISSUE TITLE
Allow selecting image family only

### ISSUE THREAD

**Issue by julianvmodesto** [jenkinsci/google-compute-engine-plugin#103]
A GCE image family will point to the latest image.

GCE plugin users should be able to select only the image project and image family instead of the image family and specific image name.

For example, the image family `ubuntu-1804-lts` points to `ubuntu-1804-bionic-v20190514`.

```
$ gcloud compute images describe-from-family ubuntu-1804-lts --project=ubuntu-os-cloud
archiveSizeBytes: '9522384640'
creationTimestamp: '2019-05-14T20:02:56.234-07:00'
description: Canonical, Ubuntu, 18.04 LTS, amd64 bionic image built on 2019-05-14
diskSizeGb: '10'
family: ubuntu-1804-lts
guestOsFeatures:
- type: VIRTIO_SCSI_MULTIQUEUE
id: '8613129354617438128'
kind: compute#image
labelFingerprint: 42WmSpB8rSM=
licenseCodes:
- '5926592092274602096'
licenses:
- https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/licenses/ubuntu-1804-lts
name: ubuntu-1804-bionic-v20190514
rawDisk:
  containerType: TAR
  source: ''
selfLink: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20190514
sourceType: RAW
status: READY
```

**Comment by rachely3n** [comment]
Have you tried using the VM templates? With VM templates, you can jsut specify an image family and it will default to the newest image.

**Comment by julianvmodesto** [comment]
That works!

**Comment by rachely3n** [comment]
Thanks for submitting this issue! It's giving us valuable insight into how users are using the plugin and how we might need to promote templates more (which is easier to configure and will lead to fewer errors).
