### ISSUE TITLE
Allow way to check if instance is ready before starting agent

### ISSUE THREAD

**Issue by andyshinn** [jenkinsci/google-compute-engine-plugin#104]
I am doing some post-boot stuff with cloud-init and startup scripts to prepare my instance for Jenkins (mounting NVMe disks and post-boot Ansible playbook). I'm actually wanting to store Jenkins workspace data on the NVMe SSD for performance reasons which means I need to wait for this to complete before the plugin can copy and start the `agent.jar`.

In 3.0.0 I was able to hack around this by creating [a custom `/usr/local/bin/java` script][1] that was picked up when the instance installer first checked output of `java -version`. The wrapper script would artificially hang until the Ansible playbook had completed (to Jenkins it just appears that the command returns very slowly).

This issue is a feature request to have a way to wait for the instance to be ready via external method. The simple fix to enable the hack again is to just move the `java -version` check before the `agent.jar` copy. But I actually think longer term it might make sense to add a check for [the cloud-init Final stage][2] using `cloud-init status --wait` or the `/var/lib/cloud/instance/boot-finished` file. This would likely account for my scenario and others where people bootstrap instances using cloud-init where there might be stuff required before the agent can actually run jobs.

[1]: https://gist.github.com/andyshinn/653e1cb6fe40616ac2dd2c5eb6b37f01
[2]: https://cloudinit.readthedocs.io/en/latest/topics/boot.html#final

**Comment by stephenashank** [comment]
Thanks for submitting this! I like the idea of waiting for cloud-init. In the meantime, I've created #105 to restore the previous functionality.

**Comment by andyshinn** [comment]
Thanks!

A slight amendment to my initial research about cloud-init. I am actually using the `google-startup-script` unit and it runs _after_ cloud-init (I assumed it would be part of cloud-init). Implementation details should take into account the startup-script service as well.

**Comment by rachely3n** [comment]
I've cut a release 3.3.0 that has #105 included. Please try it out and let us know how it goes.

**Comment by craigdbarber** [comment]
Closing this with the release of 3.3.0. Please feel free to re-open if the issue persists.

**Comment by kishorviswanathan** [comment]
After one year, I am here looking for the exact same feature. Creating a custom image with java just for Jenkins agent is an overkill. So I ended up using the hack mentioned by @andyshinn by adding `cloud-init status --wait` in the wrapper script. It would be really helpful if the plugin could wait for the cloud-init completion before checking for Java.

Please reopen this issue.
