### ISSUE TITLE
 Remote call on jenkins-workers failed. The channel is closing down or has closed down

### ISSUE THREAD

**Issue by baldeynz** [jenkinsci/google-compute-engine-plugin#111]
Hi there
We are using the google-compute-engine-plugin 3.0.0 and Jenkins 2.164.3 and we are having problems with what seems to be the plugin calling a delete on the VM before the jenkins job completes.
Google Compute Engine plugin Timeout settings for these instances are:
Launch Timeout: 300
Node Retention Time: 6

In our jenkins build logs that are errors like:

**20:48:52**  Cannot contact jenkins-workers-eciv4a: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on jenkins-workers-eciv4a failed. The channel is closing down or has closed down. this happens in the middle of the job when there is still activity and network connectivity (confirmed via vpc flow logs)

Afer this error the job eventually times out and fails.
However in strackdriver we see that several seconds before the error above there is a delete call on that instance which seems to be coming from the plugin:

**20:48:45** 

{
 insertId:  "qxcwjoe2k5x4"  
 logName:  "projects/project/logs/cloudaudit.googleapis.com%2Factivity"  
 operation: {
  first:  true   
  id:  "operation-1559854124970-58aadd705331f-3facdafe-cec32e65"   
  producer:  "type.googleapis.com"   
 }
 protoPayload: {
  @type:  "type.googleapis.com/google.cloud.audit.AuditLog"   
  authenticationInfo: {
   principalEmail:  "jenkins@project.iam.gserviceaccount.com"    
  }
  authorizationInfo: [
   0: {
    granted:  true     
    permission:  "compute.instances.delete"     
    resourceAttributes: {
     name:  "projects/project/zones/us-central1-b/instances/jenkins-workers-eciv4a"      
     service:  "compute"      
     type:  "compute.instances"      
    }
   }
  ]
  methodName:  "v1.compute.instances.delete"   
  request: {
   @type:  "type.googleapis.com/compute.instances.delete"    
  }
  requestMetadata: {
   callerIp:  "10.2.0.94"    
   callerNetwork:  "//compute.googleapis.com/projects/project/global/networks/__unknown__"    
   callerSuppliedUserAgent:  "jenkins-google-compute-plugin Google-HTTP-Java-Client/1.24.1 (gzip),gzip(gfe)"    
   destinationAttributes: {
   }
   requestAttributes: {
    auth: {
    }
    time:  "2019-06-06T**20:48:45.**071Z"     
   }
  }
could this be a bug in the plugin or a configuration issue? Is there any way to get extra logging for the plugin that will help determine the cause?

**Comment by ingwarsw** [comment]
Switching to `3.2.0` should resolve issue..

**Comment by baldeynz** [comment]
wow, quick response, thanks.. I will try the new version.

**Comment by craigatgoogle** [comment]
@baldeynz have you had a chance to test out the 3.2.0 version?

**Comment by baldeynz** [comment]
yes it seems to be working, we havent had the issue since upgrading to 3.2.0. thanks!
