### ISSUE TITLE
Intermittent key exchange error and GCP "Internal Error" 13 on machine launch

### ISSUE THREAD

**Issue by mattdlh** [jenkinsci/google-compute-engine-plugin#112]
We have been using this plugin in Jenkins installed from [this guide](https://cloud.google.com/solutions/using-jenkins-for-distributed-builds-on-compute-engine) successfully for some time now. However recently, about 75% of the machines launched automatically by Jenkins are not successfully coming online, and leading to errors shown in the GCP logs.

We are seeing that when the launches fail, the Jenkins node logs show multiple
```
Failed to connect via ssh: The connect() operation on the socket timed out.
```
errors before the machine is terminated. We have also been intermittently been seeing "Internal Error" 13 in GCP logs, and 404 errors when Jenkins is trying to delete instances that were otherwise terminated in GCP.

We are unable to reproduce by launching machines manually with the same machine templates in GCP and connecting them to Jenkins by hand - this succeeds every time.

**Comment by craigatgoogle** [comment]
Thanks for letting us know @mattdlh 
We'll take a look and follow up with what we find.

In the meantime, could you please add a link a paste of the node log which includes a failure. Thanks.

**Comment by craigatgoogle** [comment]
Also could you please include some more information:
1. Version of the GCE plugin.
2. Version of Jenkins.
3. Version of the OAuth plugin.

Thanks.

**Comment by mattdlh** [comment]
Hey @craigdbarber thanks for the response - here is some more info as requested:

Node log: I am assuming you mean the log from inside Jenkins. It is attached as [jenkins-autolaunch-fail.log](https://github.com/jenkinsci/google-compute-engine-plugin/files/3287459/jenkins-autolaunch-fail.log) . I also have the logs from inside GCP of the API calls from Jenkins, which looks like it simply launches the machine and then deletes it. I can share those as well if you would like (just need to clean it up a bit).

Versions:

| | |
| - | - |
| Google Compute Engine Plugin  | 3.2.0 |
| Jenkins  | 2.180  |
| Google OAuth Credentials plugin | 0.8 |

**Comment by craigdbarber** [comment]
Thanks for the info @mattdlh Please do share the GCP logs if you can, any additional information would be helpful. Also, if you haven't already, please check out: https://support.cloudbees.com/hc/en-us/articles/115001416548-dedicated-JNLP-agents-formerly-slaves-get-disconnected
There might be some troubleshooting tips available there which could be of use.

**Comment by mattdlh** [comment]
Sure thing, attaching [gcp-autolaunch-fail.json.log](https://github.com/jenkinsci/google-compute-engine-plugin/files/3288056/gcp-autolaunch-fail.json.log) (note it has specific names/IDs altered for privacy).

It looks like Jenkins successfully launches the machine but then sends another call to delete it. This is an intermittent error for us as I see that occasionally the machine is successfully launched. Could Jenkins be timing out with the agent connection/check? 

Checking the logs for a successful machine launch (attached as [jenkins-autolaunch-success.log](https://github.com/jenkinsci/google-compute-engine-plugin/files/3288069/jenkins-autolaunch-success.log) ), they look the same but are not followed by a removal of the node by jenkins.

Thanks for the article, I will try a few of the suggestions there that are not specifically linked to a stack trace.

**Comment by craigdbarber** [comment]
Handing this issue off to @rachely3n who is our primary on-call engineer this week.

**Comment by mattdlh** [comment]
Thanks @craigdbarber and @rachely3n 

As an update I have tried some options from the link you shared above. Some of the cases there were not linked to a specific stack trace (as I do not see one with this error). One was the TCP timeouts, which I verified were higher than the suggested limits. The other were the `NioChannelSelector` and `JnlpSlaveAgentProtocol3`Java settings, which I tried enabling for the Jenkins master. None of these changed the outcome though, and unfortunately we are still seeing the majority of machines launched with this plugin automatically killed.

We also have another Jenkins machine that is experiencing the same issue. This Jenkins has been configured independently and uses different machines images/configs as well.

Please let me know if you would like any additional information.

**Comment by craigdbarber** [comment]
Thanks for the follow up @mattdlh 
To clarify, when you mentioned that this issue is happening with another Jenkins machine configured independently, do you mean independently of the GCE plugin?

**Comment by mattdlh** [comment]
No I mean another machine with the GCE plugin installed and set up.

**Comment by rachely3n** [comment]
Hang in there, I'm currently trying to make sense of the logs :).

Do you happen to have the instance configuration settings you're using? And do you know if this started to happen after possibly changing the plugin version or did it stay the same?

What kind of image are you using as well? The only thing I can think of with unexpected deletion is the periodic node cleanup we have, but I'm still analyzing the logs.

**Comment by mattdlh** [comment]
Thanks for investigating @rachely3n

Here are some of the instance configs, from Jenkins:
|||
|-|-|
|Launch Timeout|600|
|Node Retention Time|1|
|Usage|Only build jobs with label expressions matching this node|
|Number of Executors|1|
|Run as user|jenkins-slave|
|Remote Location||
|Java Exec Path|java|
|One-Shot - Enabled|off|
|One-Shot - Create Snapshot?|off|
|Region|us-central-1|
|Zone|us-central1-a|
|Machine Configuration - Template to use|<machine_template_name>|

And from GCP the Instance Template config:
|||
|-|-|
|Machine type|n1-standard-16 (16 vCPUs, 60 GB memory)|
|Minimum CPU platfor|None|
|External IP|Ephemeral|
|Network Service Tier|Premium|
|IP forwarding|off|
|Disk type|Standard persistent disk|
|Preemptibility|Off (recommended)|
|On host maintenance|Migrate VM instance (recommended)|
|Automatic restart|On (recommended)|

The image is created using Packer. Starting from `centos-7-v20190515` and build dependency packages are installed, swap space is created, jenkins user is created. Then the image is taken using packer and a Instance Template is created from the image using the configs above.

We will do a test with a manually created image starting from that centos7 image from GCP to narrow that part of the process down.

**Comment by rachely3n** [comment]
I'm looking at the node retention time too. @mattdlh, how long do you all expect to keep your instances running?

Also to confirm, nothing was changed (plugin version, instance configuration, vm image) between the instances working fine previously to now when a certain portion of your instances can't maintain SSH connection.

For launch failures, do you happen to have the stack trace? jenkins-autolaunch-fail.log shows a successful launch except later there is an unexpected 404.

The reason I'm asking about plugin version is because starting with 1.0.10, there was a clean lost nodes feature added. You can see more information [here](https://github.com/jenkinsci/google-compute-engine-plugin/pull/17). I wonder if there's an issue with the cleanup, though that shouldn't be the case if you've already upgraded to 3.2.0 since we've made some patches since for cleaning "lost" nodes. This is the one thing I can think of for unexpected deletion.

**Comment by mattdlh** [comment]
- Node retention time: we have 1 minute of idle time set for the nodes, since we use machines with GPUs, they can be expensive and we want to shut them down if idle at all. I can try to increase this though if you think it could be a cause?

- I am not sure about the timing of the issue starting and the plugin update. From what I can recall there was an update some time (about a week or two?) before we noticed the problem, but I am not sure if it just took us a bit to realize it.

- There is no stack trace for the launch failures. Just as in the log, it shows connected, then Jenkins sends an API to delete the machine and the next log entry in the node logs is the 404.

**Comment by rachely3n** [comment]
Also, do you think you can show me the Jenkins system log? If cleanup occurs, there will be log statements.

**Comment by rachely3n** [comment]
> There is no stack trace for the launch failures. Just as in the log, it shows connected, then Jenkins sends an API to delete the machine and the next log entry in the node logs is the 404.

O, but in the log attached,  if it says
```
Agent successfully connected and online
```
that means launch was successful.

> Node retention time: we have 1 minute of idle time set for the nodes, since we use machines with GPUs, they can be expensive and we want to shut them down if idle at all. I can try to increase this though if you think it could be a cause?

Let's try this after I see the system logs?

**Comment by mattdlh** [comment]
Yep, I will grab system logs. 

WRT the agent online - it does connect in some situations (like in the log attached), but even then Jenkins deletes the instance. Jenkins sends an API to GCE to remove the machine and it deletes the node from the nodes list; that why the 404 even after the "agent online". This all occurs relatively quickly.

**Comment by mattdlh** [comment]
We are having a lot of issues with the plugin currently due to the increased launch time service issue (I saw a message in the GCP support page but cannot find a reference to it in the status page).

I do have a couple logs of note though from the Jenkin system log, these are around launch and termination:
```
Jun 17, 2019 10:08:36 PM INFO com.google.jenkins.plugins.computeengine.ComputeEngineComputerLauncher launch
Launch will wait 600000 for operation operation-1560834514639-51acc5936-f6a48842-2e047 to complete...
Jun 17, 2019 10:10:43 PM INFO com.google.jenkins.plugins.computeengine.CleanLostNodesWork terminateInstance
Remote instance jenkins-slave-8t4btd not found locally, removing it
```
And I also noticed this, not sure if it is relevant but looks related
```
Jun 17, 2019 10:10:11 PM INFO org.jenkinsci.plugins.cloudstats.CloudStatistics getIdFor
No support for cloud-stats-plugin by class com.google.jenkins.plugins.computeengine.ComputeEngineInstance
```

**Comment by ingwarsw** [comment]
For me seems that issue is 1 minute retention time.  It basically should be longer then startup time of instances..
If you have startup time 600s then your retention should be > 10.

If you want cut costs then best idea is to set all nodes as one shot, so they will start for each build and close directly after it’s finished (but retention time still needs to be hight enough).
Starting a node should be ~ 1-2 minute so that extra added cost is minimal.

**Comment by mattdlh** [comment]
@ingwarsw makes sense. This is easy to check I will increase the times and get back shortly. The 1 minute though was working for a period of about a month though; did something change (maybe longer spin up times) that could change the outcome?

Also, what did you mean by "set all nodes as one shot"?

**Comment by mattdlh** [comment]
:tada: :tada: :tada: 
@ingwarsw that did it! Moved it up to 10mins and the machines are staying online.. Seems like such a simple thing :disappointed: I think ~5mins should be good but will play with the times to get a good fit.
I am still curious as to why this worked with the 1 minute value for about a month though?

**Comment by rachely3n** [comment]
Thanks @ingwarsw. Forgot that the node retention time also would include start up time for the VM. I will update the documentation.

@mattdlh  As to why it was working before, that's worth diving into on our side since that could really rack up costs for customers. Is it possible you can try to see if anything changed between the nodes staying online and this sudden termination (plugin update, different VM image, etc). 

I also second the one-shot feature in the instance configuration as a possible solution for your use case since agents terminate automatically after job completion.

From the documentation:

> One-Shot executors create nodes dedicated
    to a single build. Upon completion of the build the node is terminated.

[More info about one-shot here](https://wiki.jenkins.io/display/JENKINS/One-Shot+Executor)

**Comment by mattdlh** [comment]
There was an increase in the image size by about 60GB around the time of the timeouts, not sure if that increases time to launch them.
I believe the plugin version and Jenkins versions were updated to the most recent (from their previous versions) as well.

The one-shot builds is a very helpful tip.

Thank you! I will go ahead and close this issue as it is resolved now.

**Comment by rachely3n** [comment]
Cool! I think increasing the image size by 60 GB could definitely have an impact. Also possible that if you changed regions that would slow you down as well. I'm going to comb through our recent commits to make sure we didn't make code changes that lead to longer boot times somehow (I highly doubt it, but it's still worth doing). Also putting out PR to clarify node retention time.
