### ISSUE TITLE
One-Shot not functioning

### ISSUE THREAD

**Issue by sce81** [jenkinsci/google-compute-engine-plugin#124]
Hey there, i've noticed recently that the one shot feature is not functioning correctly and my jobs are all trying to load onto the same instance, despite the flag being enabled.

**Comment by stephenashank** [comment]
Hi @sce81, thanks for raising this. I have unsuccessfully attempted to recreate this bug and I'll need more information to figure out the problem, so I'd appreciate if you would answer these questions:

1. What version of the plugin are you running?
1. Are you using configuration as code or configuring through the Jenkins UI?
1. Do you have multiple instance configurations with OneShot enabled?
1. What is the value of **Instance Cap** for the Google Compute Engine Cloud which contains the configuration(s)?
1. In the one shot enabled configuration(s), what are the values set for **Node Retention Time**, **Usage** ("use this node as much as possible" or "only build jobs with label expressions matching this node"), and **Number of Executors**?

Thanks in advance.

**Comment by sce81** [comment]
What version of the plugin are you running? **3.3.0 & 3.3.2**

are you using configuration as code or configuring through the Jenkins UI?
**code - jenkins DSL pipelineJob**

Do you have multiple instance configurations with OneShot enabled? **yes**

What is the value of Instance Cap for the Google Compute Engine Cloud which contains the configuration(s)? **20**

In the one shot enabled configuration(s), what are the values set for Node Retention Time, Usage ("use this node as much as possible" or "only build jobs with label expressions matching this node"), and Number of Executors
**node retention = 10m
use this node as much as possible
executors = 3**

**Comment by ingwarsw** [comment]
Change executors to 1 and thy again..

I have no idea what will happen with more than 1 executor with one shot..
Probably it cannot stop instance because it have other executors..

**Comment by stephenashank** [comment]
I tried using two executors with one shot, with an instance cap of two. Only one instance was created, and it attempted to run both builds on the same instance. However, because the build that I ran second was shorter than the first, it finished before the first build could finish, and the instance was terminated without finishing that build.

**Comment by stephenashank** [comment]
Hi @sce81, have you had an opportunity to test out version 3.4.0 and see whether the one-shot feature is working as intended for you?

**Comment by stephenashank** [comment]
Marking this as closed after inactivity, given that the fix has been released. Let us know if there are other issues.
