### ISSUE TITLE
${WORKSPACE} is now /tmp/workspace/<job>

### ISSUE THREAD

**Issue by sce81** [jenkinsci/google-compute-engine-plugin#125]
I don't know when or how this changed from ./.jenkins-slave but it is now copying to this directory. 
i have tried manually defining /home/ubuntu/.jenkins-slave but this fails as the directory does not exist

**Comment by stephenashank** [comment]
Hi @sce81, thanks for raising this. Thisbehavior was changed with #44 and released with version 3.0.1. 

By specifying **Remote Location** in your instance configuration, you can change this from `/tmp` to any path you choose. workspace and job name are appended to the path by Jenkins. It looks like the documentation in the help file for this field is outdated so I will fix that. Thanks for bringing this to our attention.

**Comment by sce81** [comment]
great thanks.
