### ISSUE TITLE
Support user specified ssh key

### ISSUE THREAD

**Issue by jsoref** [jenkinsci/google-compute-engine-plugin#175]
#101 seems to try to set the ssh key via metadata.

Unfortunately, that isn't working for our system where another file system gets mounted over the jenkins user's home directory (which already has an ssh key that the jenkins master has been using to connect to our image-templated instances).

We'd like to be able to specify the ssh key that jenkins uses to connect to the vm.

This doesn't seem to contradict #138.

I was able to start a google-compute-engine-plugin instance node, ssh from the jenkins master (using the key we already baked into our image/overlay), copy the ssh google-compute-engine-plugin generated public key from the metadata and append it to the `~jenkins/.ssh/authorized_keys` file and w/ that, the plugin was able to connect.

I'm willing to do the work for this if you don't want to write it but are open to the code.

**Comment by pbrownrobo** [comment]
errr... seems like this was fixed in current version?

**Comment by jsoref** [comment]
Shrug. We're no longer running jenkins
