### ISSUE TITLE
Using custom SSH keys when launching an instance from a template

### ISSUE THREAD

**Issue by sbateman-fitbit** [jenkinsci/google-compute-engine-plugin#211]
We want to use the GCE plugin to launch executors using an instance template that has a user and an SSH key for the user already configured in the template. 

When the plugin tries to connect to the newly generated instance, it's trying to authenticate using an auto-generated ssh key. 
How can we edit that so it's using a specific SSH key (already added to Jenkins credentials?).

Here are the SSH keys listed in the generated instances (screenshot from google console)
![Screen Shot 2020-10-22 at 10 54 36 AM](https://user-images.githubusercontent.com/63118657/96911025-24605200-1455-11eb-8752-5dffec6ac742.png).

Here is the the agent launch console log: 
```
INFO: bootstrap
Oct 22, 2020 5:58:14 PM null
INFO: Getting keypair...
Oct 22, 2020 5:58:14 PM null
INFO: Using autogenerated keypair
Oct 22, 2020 5:58:14 PM null
INFO: Authenticating as app
```
Jenkins version: 2.249.1
GCE plugin version: 4.3.2

Thanks!

**Comment by donmccasland** [comment]
Hey there.  This is a really interesting use case, and one I think we should support.  

As a new maintainer I'm just becoming familiar with the code.  It appears that the keys used to connect to the created instance are generated each time, and that there is no way to specify otherwise.

This might be a great place to use either KMS or Secrets Manager.  How do you store your keys?

**Comment by sbateman-fitbit** [comment]
We usually have the private key stored as a credential in Jenkins of type "SSH username with private key".
We can also obtain it from Vault.

**Comment by donmccasland** [comment]
Looks like we might be able to extend
https://github.com/jenkinsci/google-compute-engine-plugin/blob/develop/src/main/java/com/google/jenkins/plugins/computeengine/ssh/SshKeysHelper.java

by using the Credentials plugin API
https://github.com/jenkinsci/credentials-plugin/blob/master/docs/user.adoc

**Comment by vishal84** [comment]
Looks like the links above are promising. Will start to take a look at this.

**Comment by sbateman-fitbit** [comment]
Awesome @vishal84! Thanks for looking into it.

**Comment by naushniki** [comment]
@vishal84 @sbateman-fitbit Any updates on this issue? Have you found any solution or workaround for it?
