### ISSUE TITLE
Improve documentation for parameter instance cap per cloud

### ISSUE THREAD

**Issue by rachely3n** [jenkinsci/google-compute-engine-plugin#36]
Referencing this [issue](https://issues.jenkins-ci.org/browse/JENKINS-52649)

Objective is to improve documentation so that users know that what they name their clouds will determine the instance cap for each cloud. [Code logic](https://github.com/jenkinsci/google-compute-engine-plugin/blob/1d72075d7cef467d6b7625fe9541ad4fa440f2bb/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineCloud.java#L230)

**Comment by craigatgoogle** [comment]
Resolved with: https://github.com/jenkinsci/google-compute-engine-plugin/pull/51
