### ISSUE TITLE
External IP Address can't be configured

### ISSUE THREAD

**Issue by BrianRossmajerAxonify** [jenkinsci/google-compute-engine-plugin#438]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.3
OS: Linux - 5.13.0-1031-gcp
Java: 17.0.10 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
ace-editor:1.1
agent-maintenance:2.163.v08874cd79262
analysis-model-api:11.15.0
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
anything-goes-formatter:19.v3e2b_1b_3e0ee5
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
bootstrap4-api:4.6.0-6
bootstrap5-api:5.3.2-3
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1144.v1425d1c3d5a_7
build-failure-analyzer:2.5.0
build-name-setter:2.4.1
build-timeout:1.32
build-with-parameters:76.v9382db_f78962
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.858.v898218f3609d
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
config-file-provider:968.ve1ca_eb_913f8c
configuration-as-code:1775.v810dc950b_514
copyartifact:722.v0662a_9b_e22a_c
credentials:1319.v7eb_51b_3a_c97b_
credentials-binding:657.v2b_19db_7d6e6d
data-tables-api:1.13.8-2
display-url-api:2.200.vb_9327d658781
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
durable-task:543.v262f6a_803410
echarts-api:5.4.3-2
email-ext:2.104
external-monitor-job:215.v2e88e894db_f8
font-awesome-api:6.5.1-2
forensics-api:2.3.0
generic-webhook-trigger:2.0.0
git:5.2.1
git-client:4.6.0
git-server:114.v068a_c7cc2574
github:1.37.3.1
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1772.va_69eda_d018d4
github-oauth:597.ve0c3480fcb_d0
google-compute-engine:4.559.v84d7e025b_f7a_
google-metadata-plugin:0.5
google-oauth-plugin:1.330.vf5e86021cb_ec
google-storage-plugin:1.360.v6ca_38618b_41f
gradle:2.9
gson-api:2.10.1-15.v0d99f670e0a_7
handlebars:3.0.8
hidden-parameter:237.v4b_df26c7a_f0e
html5-notifier-plugin:1.5
htmlpublisher:1.32
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.1-373.ve709c6871598
jacoco:3.3.5
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.18-1
joda-time-api:2.12.6-21.vca_fd74418fb_7
jquery:1.12.4-1
jquery3-api:3.7.1-1
jsch:0.2.16-86.v42e010d9484b_
json-api:20231013-17.v1c97069404b_e
json-path-api:2.9.0-33.v2527142f2e1d
junit:1256.v002534a_5f33e
kubernetes:4179.v3b_88431df708
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:0.11
ldap:711.vb_d1a_491714dc
lockable-resources:1232.v512d6c434eb_d
log-parser:2.3.3
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
momentjs:1.1.1
monitoring:1.95.0
oauth-credentials:0.646.v02b_66dc03d2e
okhttp-api:4.11.0-157.v6852a_a_fa_ec11
pam-auth:1.10
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-graph-view:215.vc0ea_557e4d6f
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2175.v76a_fff0a_2618
pipeline-model-definition:2.2175.v76a_fff0a_2618
pipeline-model-extensions:2.2175.v76a_fff0a_2618
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2175.v76a_fff0a_2618
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.1
plain-credentials:143.v1b_df8b_d3b_e48
plot:2.1.12
plugin-util-api:3.8.0
popper-api:1.16.1-3
popper2-api:2.11.6-4
prism-api:1.29.0-10
rebuild:330.v645b_7df10e2a_
resource-disposer:0.23
scm-api:683.vb_16722fb_b_80b_
script-security:1313.v7a_6067dc7087
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
snyk-security-scanner:4.0.2
sonar:2.17.1
ssh-agent:346.vda_a_c4f2c8e50
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.948.vb_8050d697fec
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
text-finder:1.26
throttle-concurrents:2.14
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.133.vfb_8a_7b_9c5dd1
uno-choice:2.8.1
variant:60.v7290fc0eb_b_cd
warnings-ng:10.7.0
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1289.va_cf779f32df0
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3853.vb_a_490d892963
workflow-cps-global-lib:612.v55f2f80781ef
workflow-durable-task-step:1317.v5337e0c1fe28
workflow-job:1385.vb_58b_86ea_fff1
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:415.v434365564324
workflow-step-api:657.v03b_e8115821b_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20

### Reproduction steps

1. Add a Cloud Instance configuration, making sure to expand 'Advanced' and choosing Network IP Stack Type of IPV4_ONLY and also choose "Attach External IPV4 address"
2. After saving the instance, edit the configuration again and note that "Attach External IPV4 Address" is now unchecked
3. Create a node using this configuration, note that it does not have an external IP address

### Expected Results

Attach External IPV4 Address should remain checked, node should start with external address

### Actual Results

Nodes can not be created with external addresses

### Anything else?

I first noticed this because we use Configuration as Code, which recently enforced the deprecation of 
`"externalAddress" => true`
so I changed to 
` "networkInterfaceIpStackMode" => { "singleStack" => { "externalIPV4Address" => true } }`
Which was accepted, but had no effect.

### Are you interested in contributing a fix?

I can help test, but I'm not familiar enough with how choices in the UI or Casc translate to the instance configurations.  At a first glance, I wonder if readResolve() is unfinished in src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java as it reads the labels but doesn't use them, and there doesn't appear to be any other way to make externalAddress true

**Comment by BrianRossmajerAxonify** [comment]
I noted that choosing dual-stack defaulted to external for IPv6 only, and checking off external IP address for both stacks also didn't persist.  This code was just changed last week in 84d7e025bf7a2ed97634846ca6db718cb045a195 
I didn't confirm whether the node would be created with an external IPv6, as when I tried to launch it there was an Oops that may or may not have been related

**Comment by Vitorspk** [comment]
same from here.

I rollback the plugin to the version 4.558

**Comment by bandi13** [comment]
I'm seeing the same problem. Can confirm rollback to version 4.558 (and checking the `Attach External IP` checkbox) fixes the issue.

My Jenkins controller is on Ubuntu 22.04. I also just switched to OpenJDK-17 from OpenJDK-11. Both exhibited an issue. If it helps for debugging, I also tried stopping Jenkins, modifying config.xml, then starting Jenkins, but the checkbox remained unchecked.

**Comment by BrianRossmajerAxonify** [comment]
@Artmorse can I get you any other info to help debug this?

**Comment by Artmorse** [comment]
For more details on my changes, you can look at this PR: https://github.com/jenkinsci/google-compute-engine-plugin/pull/434.

I used [the previous version](https://github.com/jenkinsci/google-compute-engine-plugin/releases/tag/4.558.va_28ff1201886) to make the test below.
I've configured a _GCE Cloud_ via GUI then, I checked the `Attach external IP address` field. I created a cloud node using that configuration and it worked too (my GCE instance has an IPV4 address).
After that, I upgraded the GCE plugin version to [the latest one](https://github.com/jenkinsci/google-compute-engine-plugin/releases/tag/4.559.v84d7e025b_f7a_).
After the upgrade, I went to my GCE cloud configurational its `IPV4_ONLY (single-stack)` and `Attache External IPV4 address?` fields were checked (with the [`readResolve` method](https://github.com/jenkinsci/google-compute-engine-plugin/blob/develop/src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java#L356)). I created a cloud node using that configuration and it worked too (my GCE instance has an IPV4 address).

IIUC @BrianRossmajerAxonify you've issues using CasC, this is right?

**Comment by Artmorse** [comment]
I've opened a PR to fix the introduced bug: #440.
Feel free to review it :pray:

**Comment by Artmorse** [comment]
@BrianRossmajerAxonify this issue should be fixed with the latest release: https://github.com/jenkinsci/google-compute-engine-plugin/releases/tag/4.561.vfc075cc926e3
Can you try it and close the issue if this is working as expected for you?

**Comment by BrianRossmajerAxonify** [comment]
Sorry for the delay, not sure why I missed the notifications about these comments; I'm looking at it now.  Yes, I'm using CasC and the issues it was having paralleled the ones I had manually (could not create instances with external IP, couldn't create a configuration that showed in UI as having external IP)

**Comment by BrianRossmajerAxonify** [comment]
As mentioned in #440 this appears to me to be fixed; I'll leave it open 24h to give the others time to check and comment

**Comment by BrianRossmajerAxonify** [comment]
LGTM, TYVM!

**Comment by jvanoosterom** [comment]
Thank you fixed, I lost this setting when updating another setting. So finding what was wrong was a ....
