### ISSUE TITLE
One-shot feature kills slaves of unrelated projects

### ISSUE THREAD

**Issue by mikeitup** [jenkinsci/google-compute-engine-plugin#46]
Greetings,

We've installed v2.0 on several of our jenkins masters, and encountered the following issue:

Our jenkins masters are independant instances, most teams run their own masters. But slaves are launched and run in one google project, maintained by IT. For some masters (teams), new "one-shot" feature is enabled, for others, it is not. And some remaining masters are still running older versions of the plugin without these new one-shot and snapshot features at all.

Apparently, some of the masters with one-shot enabled will start killing slaves of other masters, where one-shot is disabled, probably following some naming pattern which can be similar for different masters. As a result, some teams end up with their slaves killed by other teams' masters while jobs are still run: e.g. "Team A" slave gets killed by "Team B" master, which are two independent teams.

**Comment by rachely3n** [comment]
How are we seeing that a certain worker is killed by another team's master? Are there more stack traces I can see. What kind of labels are you using for your workers/jobs?

**Comment by ingwarsw** [comment]
@mikeitup Its not `One shot` feature that is killing your tasks but probably `Clean orphaned nodes`
See https://issues.jenkins-ci.org/browse/JENKINS-56201

To fix it just change name of could in each of jenkins instances.

**Comment by mikeitup** [comment]
@rachely3n sorry I didn't reply earlier, I think what @ingwarsw says solves our issue. Thanks!

**Comment by rachely3n** [comment]
This is interesting. I may have to work on a new feature to better distinguish instances with a particular master.
@ingwarsw so the problem is because both masters are using the same cloud name?

**Comment by ingwarsw** [comment]
@rachely3n See #51
