### ISSUE TITLE
Instance cap can be exceeded when multiple Google Clouds configured

### ISSUE THREAD

**Issue by hach-que** [jenkinsci/google-compute-engine-plugin#57]
I have this configuration:

![image](https://user-images.githubusercontent.com/504826/55194156-14dc3280-5166-11e9-9282-b4662769a57e.png)

and yet somehow Jenkins decided to fire up 3 instances?

![image](https://user-images.githubusercontent.com/504826/55194169-1d346d80-5166-11e9-9805-0eb1accd0887.png)

I have a second Google Cloud configured, with an instance cap of 2 for the linux agents.

**Comment by hach-que** [comment]
Okay, this might have been because those nodes got preempted very very quickly. It looks like none of them lasted more than a minute before they got preempted.

**Comment by hach-que** [comment]
Hmm no, even after turning off preemption, it still launched two nodes:

![image](https://user-images.githubusercontent.com/504826/55194388-be232880-5166-11e9-9613-9c25aa91446d.png)

![image](https://user-images.githubusercontent.com/504826/55194411-cc714480-5166-11e9-862d-1ed53174fb02.png)

even though the instance cap is set to 1. This looks to be a pretty bad bug.

**Comment by ingwarsw** [comment]
My experience says that it works with roughly good precision..
We have it set for 50 instances and max I saw was 52..

Issue is that we are starting new instances and they are not counted until they will start showing on listing.. which may take few seconds..

I dont think its worth making it more precise, because it will make it slower/more complicated..

**Comment by rachely3n** [comment]
@hach-que I don't know if it's worth it as stated above to make it more precise. What are your thoughts? Is this a significant problem for your use case? Looking at the code, it seems it could be a timing issue between having to terminate the instance and then provisioning new instances.
https://github.com/jenkinsci/google-compute-engine-plugin/blob/1d72075d7cef467d6b7625fe9541ad4fa440f2bb/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineCloud.java#L230

**Comment by hach-que** [comment]
In my case I'm launching 32-core Windows instances, with an instance cap of 1. So when it goes over it effectively doubles my spend on Google Cloud. For 32-core Windows instances, that's not trivial given the premium OS licensing per core.

**Comment by rachely3n** [comment]
I see, yes, the cost can really add up. I'll have to research further into this since this could involve a pretty significant code change.

**Comment by rachely3n** [comment]
With #99 recently, it seems it'll be difficult to change the timing parameters such as the following:
````-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=10000 -Dhudson.model.LoadStatistics.decay=0.2````

They need to be passed through Java. Only thing I can recommend temporarily is you'd have to have your own local build of the plugin with altered values for those above parameters?
