### ISSUE TITLE
Code Cleanup: Use builder for InstanceConfiguration

### ISSUE THREAD

**Issue by stephenashank** [jenkinsci/google-compute-engine-plugin#58]
Tech debt note: the constructor for InstanceConfiguration has gotten large enough to warrant use of a builder.

_Originally posted by @craigatgoogle in https://github.com/jenkinsci/google-compute-engine-plugin/pull/55_

Related: We should move all non-essential fields into @DataboundSetters. This would help to cut down on the constructor size.

**Comment by rachely3n** [comment]
Seconding the @DataboundSetters

**Comment by stephenashank** [comment]
Resolved with #71
