### ISSUE TITLE
Terminate on migrate for instances with GPU's attached.

### ISSUE THREAD

**Issue by rachely3n** [jenkinsci/google-compute-engine-plugin#68]
Based off: https://github.com/jenkinsci/google-compute-engine-plugin/issues/63

Should change scheduling in InstanceConfiguration.java to terminate on host maintenance only for instances with GPU's.

See https://github.com/dkozlov/google-compute-engine-plugin/commit/7b7af84ee0a2cf177b2f9be8e65c656f45d964a4 for an example

**Comment by rachely3n** [comment]
One thing I see so far as a block is how to emulate live migration in integration testing.

**Comment by stephenashank** [comment]
Decided to look into this once you mentioned it. I think this should be usable, but the documentation is pretty sparse: https://cloud.google.com/compute/docs/reference/rest/v1/instances/simulateMaintenanceEvent

It's sparse in the sense that the only explanation given both on that page and the gcloud docs page is "simulates a maintenance event". I'm 90% sure that it means your instance would behave as if a real maintenance event happened (i.e. terminate if required). The other 10% is that it may be a dry run and generate logs without actually doing anything to the instance. That should be easy to test manually at least.

**Comment by ingwarsw** [comment]
@RaphC @stephenashank The problem is not with simulating `host maintanance`
The problem is that we are trying to set wrong value for `OnHostMaintenance` field when instance gave GPU added..
By default that value is set to `migrate` but with GPU it needs to be switched to `terminate` see
https://cloud.google.com/compute/docs/gpus/#restrictions

Now using instances with GPU is available via templates.
My personal opinion is that we `should` remove support for GPUs in plugin and leave it only via templates (it never worked anyway).

**Comment by ingwarsw** [comment]
@rachely3n Why you have copied #63??
It would be much easier to have 1 thread..

**Comment by rachely3n** [comment]
@ingwarsw simulating the host maintenance in this case would just be for unit testing after I make it so that instances with GPU's terminate on migrate.

what do you mean by 

> My personal opinion is that we should remove support for GPUs in plugin and leave it only via templates (it never worked anyway).

If it's available in the templates, shouldn't I still support GPU's in the plugin?

**Comment by ingwarsw** [comment]
Plugin dont need to support GPU (and never actually did)..
If plugin supports templates most things can be done via them..

Rarely used things that are supported via plugin but could be only supported via templates (and they would made plugin bit simpler)
- GPU
- Minimum Cpu Platform

**Comment by ingwarsw** [comment]
> @ingwarsw simulating the host maintenance in this case would just be for unit testing after I make it so that instances with GPU's terminate on migrate.

But we are never testing migration..
And Im not sure we should, its GCE feature not ours..

**Comment by rachely3n** [comment]
@ingwarsw 
I'm not sure I understand what's going on here. If GPU's can be added via templates, it can be used in the plugin then. I would then want to fix the migration problem for GPU instances by terminating them.

**Comment by rachely3n** [comment]
Going to keep this at #63 since yes it is easier to just have 1 thread to track this issue.
