### ISSUE TITLE
Cannot connect to GCE slave via SSH

### ISSUE THREAD

**Issue by Rukeith** [jenkinsci/google-compute-engine-plugin#69]
I use the plugin to create a GCE Slave, but the slave is always offline.
I saw the log, it seems cannot connect to the slave via ssh.

```
just before slave jenkins-slave-916wdt gets launched ...
executing pre-launch scripts ...
Apr 12, 2019 2:31:47 AM null
FINEST: Instance jenkins-slave-916wdt is running and ready...
Apr 12, 2019 2:31:47 AM null
INFO: Launching instance: jenkins-slave-916wdt
Apr 12, 2019 2:31:54 AM null
INFO: bootstrap
Apr 12, 2019 2:31:54 AM null
INFO: Getting keypair...
Apr 12, 2019 2:31:54 AM null
INFO: Using autogenerated keypair
Apr 12, 2019 2:31:54 AM null
INFO: Authenticating as jenkins
Apr 12, 2019 2:31:55 AM null
INFO: Connecting to 35.229.250.191 on port 22, with timeout 10000.
Apr 12, 2019 2:31:56 AM null
INFO: Failed to connect via ssh: There was a problem while connecting to 35.229.250.191:22
Apr 12, 2019 2:31:56 AM null
INFO: Waiting for SSH to come up. Sleeping 5.
Apr 12, 2019 2:32:01 AM null
INFO: Connecting to 35.229.250.191 on port 22, with timeout 10000.
Apr 12, 2019 2:32:01 AM null
INFO: Failed to connect via ssh: There was a problem while connecting to 35.229.250.191:22
Apr 12, 2019 2:32:01 AM null
INFO: Waiting for SSH to come up. Sleeping 5.
Apr 12, 2019 2:32:06 AM null
INFO: Connecting to 35.229.250.191 on port 22, with timeout 10000.
Apr 12, 2019 2:32:07 AM null
INFO: Connected via SSH.
Apr 12, 2019 2:32:07 AM null
INFO: connect fresh as root
Apr 12, 2019 2:32:07 AM null
INFO: Connecting to 35.229.250.191 on port 22, with timeout 10000.
Apr 12, 2019 2:32:07 AM null
INFO: Connected via SSH.
Apr 12, 2019 2:32:07 AM null
INFO: Copying agent.jar to: /tmp
Apr 12, 2019 2:32:09 AM null
INFO: Verifying: java -fullversion
bash: java: command not found
Apr 12, 2019 2:32:09 AM null
WARNING: Java is not installed.
Apr 12, 2019 2:32:09 AM null
INFO: Launching Jenkins agent via plugin SSH: java -jar /tmp/agent.jar
Apr 12, 2019 2:32:09 AM null
WARNING: Error getting exception Exception: java.io.IOException: SSH channel is closed
```

**Comment by stephenashank** [comment]
Hi @Rukeith, thanks for submitting this.
From what it looks like the agent was connected to successfully via ssh after a couple of retries, but the agent did not have Java 8 installed. See the docs on Instance Configuration [here](https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/docs/Home.md#instance-configurations). From step 8, the image used for your agent's boot disk configuration must have Java 8 installed on the default path.

**Comment by stephenashank** [comment]
I just filed #70 which will make this information more visible up front. Let me know if if my advice resolved your issue and if you have any other suggestions to make this a better experience.

**Comment by rachely3n** [comment]
Yep, if you look at the logs, you connected fresh as root, which means a successful SSH connection.

It is a bit of oversight on our part that we assume people know they will need Java 8 to run Jenkins since it uses jar files to communicate between master and agents.

Good catch @stephenashank. I might have to update the docs as well.

You can see java was installed in the integration tests as well (files ending with IT.java in tests/) via the startup scripts.

**Comment by Rukeith** [comment]
@stephenashank Thank you, I miss those informations on the log.
