### ISSUE TITLE
When a compute instance gets preempted, the plugin should abort/reschedule the jobs that were running on the instance

### ISSUE THREAD

**Issue by hach-que** [jenkinsci/google-compute-engine-plugin#72]
Right now when an instance gets preempted, the jobs that were running on the instance just stall, with the agent in an `(offline)` status. The builds never progress and never change state, even though the underlying machine is no longer there.

Since the plugin can periodically detect that the VM no exists, it should delete the agent from Jenkins and either abort or reschedule the jobs that were running on that agent.

**Comment by ingwarsw** [comment]
@hach-que see #33, its almost done..
I just need few things to finish there..
Maybe you will have some input to questions that I raised there?

**Comment by hach-que** [comment]
Oh sweet, looking forward to having that merged.

**Comment by stephenashank** [comment]
Fixed in #113
