### ISSUE TITLE
Occasionally the plugin leaves orphaned, stopped VMs

### ISSUE THREAD

**Issue by craigatgoogle** [jenkinsci/google-compute-engine-plugin#77]
[Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-52736]

This wastes compute resources and costs.

Ideally the plugin would not do this, but in addition, having a periodic (every 5 minutes) check to go through the current VMs in the project, see which ones are tagged with "jenkins" and then automatically terminate any VMs tagged with that and not known to Jenkins. This would make it resilient against unexpected Jenkins restarts, etc. (though it should be an option in case multiple Jenkins instances share the same GCE project).

**Comment by ingwarsw** [comment]
@craigatgoogle It was already released as `1.0.9` in #17 

`(though it should be an option in case multiple Jenkins instances share the same GCE project).` this part is not released but there are #46 #51

**Comment by craigatgoogle** [comment]
Understood, thanks! Closing this issue.
