### ISSUE TITLE
Make path to java executable configurable

### ISSUE THREAD

**Issue by SchulteMarkus** [jenkinsci/google-compute-engine-plugin#91]
**Is** The path to the ```java``` executable is used hard-coded, see https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineLinuxLauncher.java#L130 and https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineWindowsLauncher.java#L129. Is is expected to find ```java``` on the $PATH.

**Feature request** Please make this path (optional) configurable.

**Use cases**
1. Java is installed on the instance to use as a Jenkins slave, but is not on $PATH (my case)
2. There are more than one Javas installed on the instance, and not the default / a specific one should be used

**Comment by stephenashank** [comment]
Hi @SchulteMarkus, with release 3.2.0, this should be addressed. It may take a few hours to reach the update center in the Jenkins plugin manager. Let us know if you experience any issues.

**Comment by SchulteMarkus** [comment]
I will have a look, probably on Monday (2019-05-20)
