### ISSUE TITLE
[Code Cleanup]: Consolidate duplicated launcher logic

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-compute-engine-plugin#96]
There exists a large degree of duplicated logic in both launch methods for Linux and Windows. Ideally this logic should be consolidated. See:
https://github.com/jenkinsci/google-compute-engine-plugin/blob/a6ec3414e92592d63d5b66e4b5d8362956e0c12b/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineLinuxLauncher.java#L91
https://github.com/jenkinsci/google-compute-engine-plugin/blob/a6ec3414e92592d63d5b66e4b5d8362956e0c12b/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineWindowsLauncher.java#L90

**Comment by stephenashank** [comment]
Resolved in #105 and #133
